Milestone 1: Finished Setup
nikoescobal/tic-tac-toe pull request #1
Opened 2021-01-21 09:56 UTC by nikoescobal

- Added lib and bin directories
- Added .gitkeep and main.rb
- Configured main.rb file to be executable

2021-01-21 11:02 UTC, lekegitrepo requested changes
## Status: Changes Required! :recycle:
### Hi @nikoescobal :clap: :clap:
#### Good job so far :+1: However, you to implement the following requirement before this project can be approved. Check my comments below :point_down:

#### 1) LINTER:
 - Enable linter for this Pull Request, and fix the rubocop errors.

#### _Reviewed by Temitayo Adeleke_

2021-01-21 11:02 UTC, lekegitrepo commented on bin/main.rb
> +puts "Hello!"
- **_[Optional] This should be "Hello World"_**

2021-01-22 09:14 UTC, Georjane requested changes
## Status: Changes Required 🔁 🚫
### Hi Team 🙌
Your setup for the Tic Tac Toe game project is ready but you have to set up your linters for the project before it gets approved, just like the previous Code Reviewer requested. 

Feel free to reach out to me on Slack if you have any questions, Witah Georjane 
Goodluck on your project and Happy Coding 💻

2021-01-22 09:49 UTC, NtwaliHeritier approved these changes
### STATUS: APPROVED✔✔
Good work team. 
Move on to the next milestone.

2021-01-28 10:06 UTC, merged